### ISSUE TITLE
Access to code from PhUSE x FDA docker pilot

### ISSUE THREAD

**Issue by dgkf** [RConsortium/submissions-wg#1]
At today's meeting, Paul mentioned a pilot that he and I worked on to share docker containers. It would be great if I could share that code with you all. I reached out to the lead from the PhUSE working group to see if we can get that code uploaded somewhere where I can share it. 

A brief summary of what was done:
- Delivery of a `docker-compose` build script, chosen for transparency and to adhere to plain-text restrictions of delivery content. It consisted of:
   - base image based on rocker shiny+tidyverse image
   - a small cohort of packages to install 
   - a mock analysis and companion shiny app
   - data access (which ended up being the problematic piece of the puzzle)
- We encountered a few data access woes:
   1. we first attempted to mount a data directory within the eCTD, which prompted for escalated administrator privileges on windows machines - not an acceptable solution
   2. the second attempt was to build the data into the container image, which we were unfortunately not able to fully test before Paul had to move on to other priorities.

Overall, I still have confidence that this method could work, but, as Paul mentioned, the "it works on my machine" method of trying to debug across platforms and administrated systems is both frustrating and time intensive. Remotely teasing apart docker-related issues from system adminstration restrictions without a clear picture of the systems constraints was quite a challenge.

**Comment by joseph-rickert** [comment]
Hi Doug,
Thanks for contributing your summary of work done. We really need to
coordinate the experiences of groups working on the problem in order to
find a way to move forward. I included your comments as an addendum to the
minutes before I saw
that you also put your comments in the GitHub issues. - a special thanks
for seeding this :)

Best regards,
Joe

Joseph B. Rickert
RStudio R Community Ambassador
R Consortium Director
Cell: 408.489.0566
