### ISSUE TITLE
Comments for Blog post: Crucial Role of Release Control In R For Health Care Organizations

### ISSUE THREAD

**Issue by joseph-rickert** [RConsortium/submissions-wg#117]
Please add comments on the R Consortium Blog Post under this issue.

**Comment by geoskiad** [comment]
Question related to this statement: "One suggestion that has gained some traction is that sponsors use the previous minor and latest patched R version for a submission." - How close to a DB lock would one switch the R version used for the CSR analysis? Even in a change cycle of 2 times per year, considering that you do not want to risk timelines due to a last minute change of R version, by the time you reach "submission" you may have quite an "old" R version. Is anyone aware of any potential issues/problems (from Regulatory perspective) with this until now? Or do I misinterpret something here? Note: I have zero personal experience with R based submissions.

**Comment by bms63** [comment]
> Question related to this statement: "One suggestion that has gained some traction is that sponsors use the previous minor and latest patched R version for a submission." - How close to a DB lock would one switch the R version used for the CSR analysis? Even in a change cycle of 2 times per year, considering that you do not want to risk timelines due to a last minute change of R version, by the time you reach "submission" you may have quite an "old" R version. Is anyone aware of any potential issues/problems (from Regulatory perspective) with this until now? Or do I misinterpret something here? Note: I have zero personal experience with R based submissions.

I would not switch R versions between a lock and CSR unless there is some huge risk to the sponsor and regulatory agency.  Hopefully, very unlikely to ever happen!  

I think engaging with the reviewers early is very important especially if the study is going to happen over many years.  The regulatory agencies can usually get access to R versions and prepare accordingly.

**Comment by madprogramer** [comment]
This blog post resonates a lot with me. Back in the Old World, I know that there is some work being done on [CE approval](https://europa.eu/youreurope/business/product-requirements/labels-markings/ce-marking/index_en.htm) of medical software. Here too, reproducibility of results is a big expectation similar to the FDA approval processes.

I don't think R versioning is _as important_ as it was a few years ago. Namely, [renv](https://rstudio.github.io/renv/) has matured a good deal. So I would say I am leaning towards the `Roche` and `Eli Lilly` way of doing things.
