### ISSUE TITLE
Address Comments from Submission Package review

### ISSUE THREAD

**Issue by waddella** [RConsortium/submissions-wg#51]
comments from #47 

- [ ] example comment
- [ ] other example

**Comment by lengning** [comment]
Thank you all for the comments. Please see below a summarization on comments being addressed and not addressed

Comments addressed
- submit .r for the 4 programs, instead of .txt
- good practice: KM good practice, etc
- language improvement in ADRG, cover letter, etc
- typos in ADRG appendix

Comments that won't be addressed
- inconsistencies between tables : this is intended to test out different tools and different standards different companies are following. will clarify in the report
- company specific requirement (header, footnote, decimal, etc)
- ADRG formating good practice(TOC, hyperlink, etc)  
- validation document: this pilot will not try to set an example of "validated r package" so validation will be out of scope. also indicated in the cover letter

**Comment by elong0527** [comment]
The two github repo has been updated to reflect comments w.r.t define.xml and analysis program. 

- https://github.com/RConsortium/submissions-pilot1
- https://github.com/RConsortium/submissions-pilot1-to-fda

ADRG is updated to address comments to rerun the code

- https://docs.google.com/document/d/1UAZMY0iMfJiwlQVCM5mJvVgXDR7c5YRBUEj1kSxxK70/edit
- Note: the steps is only for code saved in https://github.com/RConsortium/submissions-pilot1-to-fda/tree/main/m5/datasets/rconsortiumpilot1/analysis/adam/programs
