### ISSUE TITLE
Pilot 2 shiny app: call for review

### ISSUE THREAD

**Issue by lengning** [RConsortium/submissions-wg#80]
Please review 

1. the cover letter: [R consortium R submission pilot 2 - cover letter.pdf](https://github.com/RConsortium/submissions-wg/files/8643167/R.consortium.R.submission.pilot.2.-.cover.letter.pdf), [google doc version](https://docs.google.com/document/d/14NqSw2syOK7sh6pm0tJ7N1zdAlpTcWHRUubz2T3V9Us/edit)

2. the deployed [shiny app](https://genentech.shinyapps.io/FDA-app/)

Please feel free to leave your high level feedback in this issue, and specific bug reports etc in the [pilot2 repo](https://github.com/RConsortium/submissions-pilot2/issues)

Thank you!

code/ADRG review will be conducted in ~June

**Comment by nanxstats** [comment]
Thanks Ning. I added a few minor suggestions, attached here.
[R.consortium.R.submission.pilot.2.-.cover.letter.pdf](https://github.com/RConsortium/submissions-wg/files/8646029/R.consortium.R.submission.pilot.2.-.cover.letter.pdf)

**Comment by SHAESEN2** [comment]
Thank you for sharing. Nice work done by the team. I had a few comments.

**General**
- Should we think about a way for the FDA to (re)view the code behind the tables ? Personally, I think shinymeta works well for this. 
- Titles for the tables and explanatory footnotes might be helpful in interpretation of the tables. The description on the first page is not sufficient and difficult to remember (eg imagine you have 500 outputs to generate and the reviewer needs to go back and forth to the first page.
- On the first page, should we include more information about the R version and the packages? We should at least mention the study and its purpose (imagine the reviewer wants to compare an Interim analysis with a resubmission and has the two apps open at the same time).
- With regards to navigation between the different modules, how will you organize the app if you have 20 demographic tables? Will they all get a subtab under "Demographic" or will each table gets his own tab?

**Demographic table**
- Should we allow the FDA reviewer to change the analysis set (eg FASFL instead of ITTFL)?
- Can we allow the reviewer to save the table eg in HTML/PDF/TXT/... so that they can view results side-by-side? (eg cross-reference table/graph for the safety population). 

**KM plot**
- You need to foresee more height/less width on the HTML page. We are working on a new release of visR to improve the distance between table and graph (release within the next 2 months) 
- Why do we have a filter for the KM table? The only two filters that would make sense are ADTTE.PARAM/PARAMCD, the population flags and subgroups. However, the app does not seem to allow subgroup analysis eg If I choose ADSL.SEX then the graph display does not change.  One more interesting filter could be to request n.censor/n.event/n.risk for the risktable.

**Primary table**
- Primary table: I would use bold for the visit labels to make the table easier to read
- Footnotes are not showing. I am referring to the numbers in brakcets eg [1][2]. If those are the contrasts then I would add a footnote to make that clear.
- It is not clear for which population this table is (N is not matching with other tables)

**Efficacy table**
- I prefer footnotes rather than hoover text
- p-value (not p-Value)

**Comment by SHAESEN2** [comment]
@lengning do you want me to put these as issues in the pilot 2 repo?

**Comment by lengning** [comment]
Putting them here is perfectly fine :) thank you!
